Plotly is a library that allows you to create interactive plots that you can use in dashboards or websites (you can save them as html files or static images).

In [24]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio

In [25]:
# renderer for VS Code notebooks
pio.renderers.default = 'vscode'

In [26]:
#creating fake data
df = pd.DataFrame(np.random.randn(100,4), columns = 'A B C D'.split())

In [10]:
df.head()

          A         B         C         D
0  0.276953 -0.235467  0.160113 -0.024886
1 -0.484672  0.523390 -1.453273  0.186198
2  0.862788 -1.569063 -0.606853 -1.635857
3  0.427832  0.094857 -0.688778 -0.732308
4  0.077778  0.405040  0.070073 -0.435874

In [11]:
#dictionary creating
d = {'Category':['A','B','C'], 'Values':[32,43,50]}

In [14]:
d['Values']

[32, 43, 50]

In [15]:
df2 =pd.DataFrame(d)

In [16]:
df2

  Category  Values
0        A      32
1        B      43
2        C      50

# Scatter

In [27]:
# scatter plot
fig = px.scatter(
    df,
    x='A',
    y='B',
    title='Scatter Plot of A vs B'
)

# show plot
fig.show()

## Bar Plots

In [28]:
fig = px.bar(df2, x= 'Category',y = 'Values', title='Bar Plot')
fig.show()

In [29]:
px.bar(df2, x='Category', y='Values')

In [30]:
px.bar(df.count())

## Boxplots

In [32]:
px.box(df)

# 3D Surface

In [33]:
#creating a dataframe with 3 features
df3 = pd.DataFrame({'x':[1,2,3,4,5],'y':[10,20,30,20,10],'z':[5,4,3,2,1]})

In [36]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Surface(z=df3.values,
                                 colorscale='RdYlBu')])

fig.show()

In [42]:
px.histogram(df, x='A', nbins=25)

In [45]:
px.scatter_matrix(df)